package.json

Should solve the weird replication issues. See https://github.com/electron/electron/issues/5851 for more details

downgrade electron to 1.1.3

---

app/shell-window/ui/navbar.js

This is a simplified PR for https://github.com/pfrazee/beaker/issues/97#issue-178170054
The PR only fix issues related to Chinese IME on `navbar`.
Issues mentioned at https://github.com/pfrazee/beaker/pull/98#issuecomment-248633956 can be reproduced on current master. I'll open another issue to track those problems.
fix #97

Chinese IME support on navbar

---

README.md
app/background-process.js
app/background-process/dbs/bookmarks.js
app/background-process/dbs/history.js
app/background-process/dbs/settings.js
app/background-process/dbs/sitedata.js
app/background-process/plugins.js
app/background-process/protocols/beaker-favicon.js
app/background-process/ui/permissions.js
app/background-process/ui/window-menu.js
app/background-process/ui/windows.js
app/env.js
app/lib/bg/sqlite-tools.js
app/log.js
app/shell-window/pages.js

Adds env var:
`beaker_log_level`: how much logging to put out. Must be: 'trace', 'debug', 'info', 'warn', or 'error. Default: 'warn'.

Make log level configurable via env var

---

app/lib/fg/color-thief.js
app/lib/fg/img.js
app/shell-window/pages.js
app/shell-window/ui/tabs.js
app/stylesheets/shell-window/chrome-tabs.less
app/stylesheets/shell-window/toolbar-actions.less
app/stylesheets/shell-window/toolbar.less

This PR adds a little pizzazz to the tabs, by animating them and adding the dominant color as a bottom border.

Add animated favicons on tabs

---

app/shell-window/ui/tabs.js
app/stylesheets/shell-window/chrome-tabs.less
app/stylesheets/shell-window/toolbar.less

Add slanted edges to the browser tabs

---

app/shell-window/ui/tabs.js
app/stylesheets/shell-window/chrome-tabs.less

Previously, there was a bug where the edges of tabs would change angle depending on the width of the tab. This solves that bug.

Fix: browser tabs now render consistently regardless of width

---

app/shell-window/ui/navbar.js

Solves https://github.com/beakerbrowser/beaker/issues/134 and makes sure there's never a case where you can't navigate to a specific address via the url bar

Improved navbar behaviors

---

app/webview-preload.js

Disable CSP bypass in dat sites 

---

app/background-process.js
tasks/start.js

Closes https://github.com/beakerbrowser/beaker/issues/149

Fix devtool crash

---

app/background-process/dbs/history.js
app/shell-window/pages.js

* don't log multiple consecutive visits to the same url
* update title in history if it's changed within 15s after page load and the URL doesn't change
* sort history by ts instead of rowid
fix #70

Smarter History

---

app/background-process/dbs/archives.js
app/background-process/networks/dat/web-api.js
tests/dat-web-api-test.js

Adds the dat permission management which is specced in https://github.com/beakerbrowser/beaker/issues/155

Add dat-web-api write permissions

---

README.md
app/background-process/networks/dat/web-api.js
app/lib/const.js
tests/dat-web-api-test.js

Closes some items in https://github.com/beakerbrowser/beaker/issues/156

Add quota limit to the dat web api

---

app/background-process/browser.js
app/background-process/dbs/bookmarks.js
app/background-process/dbs/history.js
app/background-process/dbs/sitedata.js
app/background-process/protocols/dat.js
app/background-process/ui/downloads.js
app/background-process/web-apis.js
app/lib/bg/rpc.js
app/package.json

Closes https://github.com/beakerbrowser/beaker/issues/177

Add global permission checks to the internal RPC methods

---

app/background-process/networks/dat/dat.js
app/background-process/networks/dat/helpers.js
app/background-process/networks/dat/web-api.js
app/builtin-pages/views/archives.js
app/lib/const.js
app/shell-window/dat-web-api.js
tests/dat-web-api-test.js

Closes https://github.com/beakerbrowser/beaker/issues/164

Dat api fixups

---

app/background-process/dbs/archives.js
app/background-process/dbs/archives.md
app/background-process/networks/dat/dat.js
app/builtin-pages/com/archives-list.js
app/builtin-pages/views/archive.js
app/lib/strings.js
app/shell-window/dat-web-api.js
app/stylesheets/com/archives.less
app/stylesheets/views/archive.less
tests/dat-web-api-test.js
tests/scaffold/test-runner-dat/dat.json

Closes https://github.com/beakerbrowser/beaker/issues/176
That green might be a bit much. We'll see.

Add created-by metadata to dats

---

app/shell-window/ui/navbar.js

default localhost to http

---

app/background-process/browser.js
app/background-process/networks/dat/dat.js
app/background-process/networks/ipfs/ipfs.js
app/background-process/protocols/fs.js
app/lib/mime.js
app/shell-window/ui/navbar/site-info.js
app/stylesheets/shell-window/toolbar-dropdown.less

- Add protocol icon to the navbar
- Fix bug where site permissions dropdown was not showing titles (actually a dat bug)
- Fix IPNS resolution
- Fix index.html lookup on directories
- Fix exception-alert when files dont have data

Collection of IPFS fixes and improvements

---

app/builtin-pages/views/favorites.js
app/shell-window/ui/navbar/drop-menu.js

Add support links to the navbar drop menu

---

README.md
app/background-process.js
app/background-process/api-manifests/internal/dat-internal.js
app/background-process/bkr.js
app/background-process/dbs/archives.js
app/background-process/dbs/archives.md
app/background-process/networks/dat/dat-manifest.js
app/background-process/networks/dat/dat.js
app/builtin-pages/com/archives-list.js
app/builtin-pages/views/archive.js
app/lib/const.js
app/package.json
app/stylesheets/com/archives.less
app/stylesheets/views/archive.less
tests/bkr-test.js
tests/dat-test.js
tests/dat-web-api-test.js
tests/package.json

This PR adds a JSON-RPC server which the [bkr cli](https://github.com/beakerbrowser/bkr) can interact with. It also involves a lot of small behavioral changes, to accommodate bkr.
Still todo before merging:

Add server for bkr cli

---

app/background-process/bkr.js
app/package.json

Now uses semvers from package.json

improve version negotiation with bkr

---

app/background-process/ui/windows.js

Adds beaker logo to the ubuntu 16.10 unity startbar.

fix for #250 - show logo in ubuntu startbar

---

app/background-process/networks/dat/dat.js
app/lib/const.js
app/package.json

The commit messages are descriptive. This improves the consistency of discovery and connection establishment for dats.

Improvements to dat networking

---

app/builtin-pages/com/archive-view.js
app/builtin-pages/views/archives.js
app/shell-window/pages.js
app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/drop-menu.js
app/shell-window/ui/navbar/site-info.js
app/stylesheets/shell-window/toolbar-input-group.less
app/stylesheets/shell-window/toolbar.less

Some needed UI updates to the navbar. Some of it is aesthetics, and some of it is added functionality for dat sites.
In order:
- Toggle live-reloading
- Fork this site
- Save this site for offline
- Bookmark this page

Navbar updates

---

app/background-process/networks/dat/dat.js

PR is waiting on updates to hyperdrive-import-files. It needs to do a hash comparison to accurately reflect updates.

Add dryRun to writeArchiveFileFromPath

---

app/background-process/networks/dat/dat.js
app/package.json

Only add files to dats that have changed content.

---

app/background-process/api-manifests/internal/dat-internal.js
app/background-process/networks/dat/dat.js
app/background-process/protocols/dat.js
app/builtin-pages/com/archive-view.js
app/builtin-pages/views/archives.js
app/lib/mime.js
app/shell-window/pages.js
app/shell-window/ui/tabs.js

Collection of UI improvements. See commits for details.
Closes #271 and #272.

Ui fixes 0.6.1

---

app/shell-window/ui/tabs.js

X button on tabs now says "Close tab", and the add tab tooltip is "Open new tab"

Fix tooltips on tab close buttons (close #270)

---

app/shell-window/ui/navbar/site-info.js
app/stylesheets/shell-window/toolbar-dropdown.less

Fixes an issue reported at https://github.com/beakerbrowser/beaker/pull/283#issuecomment-278339564

Fix: site info dropdown now renders again

---

app/background-process/bkr.js
app/background-process/networks/dat/dat.js
app/background-process/open-url.js

Blocked by https://github.com/juliangruber/hyperdrive-import-files/pull/47

Bkr improvements

---

app/background-process/bkr.js
app/background-process/networks/dat/dat.js

Part of https://github.com/beakerbrowser/bkr/issues/9
Can now `bkr clone <domain>`, and can also clone dats that are not yet downloaded

Better bkr clone

---

app/builtin-pages/views/history.js

set a default option for the clear history select

---

app/shell-window/ui/tabs.js

Hi! I made a couple little improvements to the tabs so it's a bit closer to other browsers 😄  :
* Add middle-click to close tab
* Add "Reopen Closed Tab" to tab context menu

Tabs improvements

---

app/shell-window/pages.js
app/shell-window/ui/tabs.js
app/stylesheets/shell-window/webviews.less
package.json
tasks/build/build.js

Blocked by:
- https://github.com/electron/electron/issues/8621
- https://github.com/electron/electron/issues/8610
Todo after/during upgrade:
- Better zooming https://github.com/electron/electron/pull/8537
- See if the invalidate method can solve the "webviews created off screen" problem

Electron 1.6.0

---

app/background-process/ui/windows.js
app/shell-window.html
app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/drop-menu.js
app/shell-window/ui/navbar/site-info.js
app/shell-window/ui/tabs.js
app/stylesheets/shell-window/chrome-tabs.less
app/stylesheets/shell-window/toolbar-actions.less
app/stylesheets/shell-window/toolbar-input-group.less
app/stylesheets/shell-window/toolbar.less

- Add vibrancy (semi-transparency) (OSX)
- New icons
- Modified tab coloring

Improve the browser UI

---

app/builtin-pages/com/archive-files.js
app/builtin-pages/fork-archive-modal.js

Show current directory path in site library

---

app/builtin-pages/com/archive-files.js
app/stylesheets/components/files-list.less

Improve visual differentiation of folders in the sites library

---

app/builtin-pages/com/archive-files.js
app/stylesheets/components/files-list.less

Library - Files view, show all parent ancestry as clickable links

---

app/background-process/protocols/dat.js
app/markdown-renderer.js
app/shell-window/pages.js

- Fallback to index.md if index.html is not found
- Improve rendering styles
- Add support for a persistent `/nav.md`, with automatic generation if none is found
Example:

V0.7 better markdown

---

app/background-process/protocols/dat.js
app/markdown-renderer.js
app/shell-window/pages.js

- Add header anchor links
- Fix the auto-genned nav
- Style improvements
- Update resolution rules if no file is provided: index.html > index.md > readme.md

V0.7 more markdown improvements

---

app/shell-window/ui/tabs.js
app/stylesheets/base/colors.less
app/stylesheets/shell-window/chrome-tabs.less

Update tabs to look more distinct, less chrome-like

---

app/shell-window/ui/tabs.js
app/stylesheets/shell-window/chrome-tabs.less

More tab style improvements

---

app/background-process/networks/dat/library.js
app/background-process/protocols/beaker.js
app/background-process/web-apis/archives.js
app/builtin-pages/network.html
app/builtin-pages/views/network.js
app/builtin-pages/views/start.js
app/lib/api-manifests/external/archives.js
app/lib/fg/sparkline.js
app/lib/web-apis/beaker.js
app/package.json
app/shell-window/pages.js
app/shell-window/ui.js
app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/drop-menu.js
app/stylesheets/builtin-pages/network.less
app/stylesheets/builtin-pages/setup.less
app/stylesheets/builtin-pages/start.less
app/stylesheets/shell-window/toolbar-actions.less
app/stylesheets/shell-window/toolbar-dropdown.less
app/stylesheets/shell-window/toolbar-input-group.less
app/stylesheets/shell-window/toolbar.less
tasks/build/build.js

This PR adds `beaker://network` as well as peer-counts in the URL bar and start page.

V0.7 p2p stats

---

app/builtin-pages/views/network.js
app/builtin-pages/views/start.js
app/stylesheets/base/colors.less
app/stylesheets/builtin-pages/start.less

Add a shelf to the start page

---

app/background-process/dbs/archives.js
app/builtin-pages/views/network.js
app/builtin-pages/views/start.js
app/shell-window/pages.js
app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/drop-menu.js
app/stylesheets/builtin-pages/network.less
app/stylesheets/builtin-pages/start.less
app/stylesheets/shell-window/toolbar-dropdown.less

V0.7 various improvements

---

app/builtin-pages/com/editor-header.js
app/stylesheets/builtin-pages/components/editor-files-sidebar.less
app/stylesheets/builtin-pages/components/editor-header.less
app/stylesheets/components/buttons.less

Screenshot in reference to [this commit](https://github.com/beakerbrowser/beaker/commit/e787dbe8b7187b1cde257e0905cdcb1a265a381a).

v0.7 editor touchups

---

app/builtin-pages/com/editor-bkr-popup.js
app/builtin-pages/com/editor-files-list.js
app/stylesheets/base/typography.less
app/stylesheets/builtin-pages/components/editor-bkr-popup.less
app/stylesheets/builtin-pages/components/editor-files-sidebar.less
app/stylesheets/builtin-pages/components/editor-share-popup.less
app/stylesheets/builtin-pages/editor.less

Add popup in editor for bkr prompt

---

app/builtin-pages/views/start.js
app/stylesheets/builtin-pages/start.less

This updates the start page shelf.

v0.7 start shelf

---

app/background-process/browser.js
app/background-process/dbs/settings.js
app/background-process/protocols/beaker.js
app/builtin-pages/views/settings.js
app/builtin-pages/views/start.js
app/lib/api-manifests/internal/browser.js
app/lib/fg/color-thief.js
app/stylesheets/builtin-pages/settings.less
app/stylesheets/builtin-pages/start.less

Closes #401 
@fredhampton let us know what you think of this once you get a chance to try it out!

Add setting to set background image on beaker://start

---

app/background-process/networks/dat/library.js
app/background-process/protocols/dat.js
app/background-process/web-apis/archives.js
app/background-process/web-apis/dat-archive.js
app/builtin-pages/views/library.js
app/package.json
app/shell-window/pages.js
app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/drop-menu.js
app/stylesheets/shell-window/toolbar-input-group.less
tests/dat-archive-web-api-test.js

Adds support for versioned Dat URLs using the + delimiter. See https://github.com/pfrazee/parse-dat-url

V0.7 versioned urls

---

app/background-process/protocols/dat.js
app/background-process/web-apis/dat-archive.js
app/builtin-pages/views/library.js
app/lib/error-page.js

Improves handling of dats that fail to load

V0.7 dat timeouts

---

app/background-process/browser.js
app/background-process/protocols/beaker.js
app/background-process/ui/modals.js
app/builtin-pages/prompt-modal.html
app/builtin-pages/views/prompt-modal.js
app/stylesheets/builtin-pages/prompt-modal.less
app/webview-preload.js
app/webview-preload/navigator-permissions-api.js
app/webview-preload/prompt.js
tasks/build/build.js

Implement window.prompt (close #399)

---

app/background-process/networks/dat/library.js
app/background-process/web-apis/archives.js
app/builtin-pages/views/create-archive-modal.js
app/builtin-pages/views/library.js
app/lib/api-manifests/internal/archives.js
app/lib/web-apis/beaker.js
app/package.json
tests/dat-archive-web-api-test.js

A few performance improvements, fixes to how dat.json is handled, and adds the ability to change the staging path after creation

V0.7 some dat fixups

---

app/shell-window/ui/navbar/site-info.js
app/stylesheets/shell-window/toolbar-dropdown.less
app/stylesheets/shell-window/toolbar-input-group.less

Update security info dropdown

---

app/shell-window/pages.js
app/shell-window/ui/tabs.js

- Set tab title correct on failed load
- Fix a case where entering a URL wouldnt load a page, if the tab was new

V0.7 more tab fixes

---

app/builtin-pages/com/archive-changes.js
app/builtin-pages/views/library.js
app/stylesheets/base/colors.less
app/stylesheets/builtin-pages/library.less
app/stylesheets/components/buttons.less

Update publishing flow

---

app/background-process/networks/dat/directory-listing-page.js
app/shell-window/pages.js

Make monospace fonts consistent

---

app/builtin-pages/views/library.js
app/stylesheets/builtin-pages/library.less

I know we said we weren't going to prioritize this, but it was becoming enough of a pain point for me that I decided to do it anyway 😄

Make the library responsive

---

app/builtin-pages/views/start.js
app/stylesheets/builtin-pages/start.less

Update release notes styles

---

app/markdown-renderer.js
app/shell-window/pages.js

- Allow html tags
- Improve some styles

A few markdown rendering tweaks

---

app/builtin-pages/views/library.js
app/stylesheets/builtin-pages/library.less

Add 'create site' to the library

---

app/background-process/networks/dat/library.js
app/background-process/protocols/beaker.js
app/background-process/web-apis/archives.js
app/builtin-pages/swarm-debugger.html
app/builtin-pages/views/library.js
app/builtin-pages/views/start.js
app/builtin-pages/views/swarm-debugger.js
app/lib/api-manifests/internal/archives.js
app/lib/error-page.js
app/lib/web-apis/beaker.js
app/lib/web-apis/dat-archive.js
app/shell-window/pages.js
app/stylesheets/builtin-pages/swarm-debugger.less
tasks/build/build.js

Add swarm debugger

---

app/background-process.js
app/background-process/protocols/beaker.js
app/background-process/ui/basic-auth.js
app/background-process/ui/modals.js
app/background-process/web-apis/dat-archive.js
app/builtin-pages/basic-auth-modal.html
app/builtin-pages/views/basic-auth-modal.js
app/lib/electron.js
app/stylesheets/builtin-pages/basic-auth-modal.less
tasks/build/build.js

Add basic-auth modal (close #473)

---

app/background-process/web-apis/dat-archive.js

Fix: Don't let the permissions prompt cause operations to timeout

---

app/package-lock.json
app/package.json

This fixes a bug in live-reloading of remote dats

Bump pauls-dat-api to 4.2.2

---

app/background-process/protocols/dat.js
app/package-lock.json
app/package.json

Fixes peer counts in the start and library pages

Fix peer counts in the UI, and some etc

---

README.md

README.md: Added missing Linux dependencies

---

app/background-process/web-apis/dat-archive.js
app/builtin-pages/views/library.js
app/package-lock.json
app/package.json

This PR speeds up diffing in the library by not recursing into folders that are being created or removed. It causes you to see less detail in the diff, but gives much better perf

Use shallow diffing in the library staging area

---

app/background-process/protocols/beaker.js
app/builtin-pages/com/files-list.js
app/builtin-pages/dat-sidebar.html
app/builtin-pages/views/dat-sidebar.js
app/builtin-pages/views/library.js
app/shell-window.html
app/shell-window/pages.js
app/shell-window/ui.js
app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/dat-sidebar.js
app/shell-window/ui/sidebar.js
app/stylesheets/builtin-pages/dat-sidebar.less
app/stylesheets/components/dropdown.less
app/stylesheets/shell-window.less
app/stylesheets/shell-window/dat-sidebar.less
app/stylesheets/shell-window/toolbar-dropdown.less
app/stylesheets/utils/decorators.less
app/webview-preload/locationbar.js
tasks/build/build.js

This adds the Dat sidebar on Dat websites.
There are still some TODO items, but I'll leave them to you @pfrazee since they all are related to managing the open/closed state of the sidebar

Dat sidebar (WIP)

---

app/builtin-pages/views/library.js
app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/drop-menu.js
app/stylesheets/builtin-pages/library.less

Summary:
- Remove Dat contextual items from dropdown menu
- Live reloading is now in URL bar
- Swarm debugger updates in `beaker://library`

A few UI updates

---

app/background-process/networks/dat/library.js
app/background-process/protocols/dat.js
app/background-process/ui/window-menu.js
app/builtin-pages/views/dat-sidebar.js
app/package-lock.json
app/package.json
app/shell-window/command-handlers.js
app/shell-window/ui/sidebar.js
app/stylesheets/base/colors.less
app/stylesheets/builtin-pages/dat-sidebar.less
app/stylesheets/shell-window/dat-sidebar.less

Closes https://github.com/beakerbrowser/beaker/issues/542

Sidebar updates

---

app/shell-window/pages.js
app/shell-window/ui/navbar/dat-sidebar.js
app/shell-window/ui/sidebar.js
app/stylesheets/shell-window/dat-sidebar.less
app/stylesheets/shell-window/toolbar-actions.less

Hide sidebar on non archives

---

app/background-process/browser.js
app/background-process/networks/dat/library.js
app/background-process/web-apis/archives.js
app/builtin-pages/views/dat-sidebar.js
app/builtin-pages/views/library.js
app/lib/api-manifests/internal/archives.js
app/lib/web-apis/beaker.js
app/shell-window/ui/navbar/drop-menu.js

Better archive delete prompt

---

app/builtin-pages/com/files-list.js
app/builtin-pages/views/library.js
app/stylesheets/builtin-pages/components/files-list.less
app/stylesheets/builtin-pages/library.less

This is a major overhaul of the library archive view:
- Networking and staging is moved to tab
- Staging notification added to files listing
- Move title and description to metadata tab, add inline editing
- Remove view site button, replace with import files button
- Update `.files-list` color
@pfrazee all that's left to do is wire up the import files button

Library updates

---

app/builtin-pages/com/files-list.js
app/builtin-pages/views/dat-sidebar.js
app/builtin-pages/views/library.js
app/shell-window/ui/sidebar.js
app/stylesheets/builtin-pages/dat-sidebar.less
app/stylesheets/builtin-pages/library.less
app/stylesheets/components/buttons.less
app/stylesheets/components/messages.less
app/stylesheets/shell-window/dat-sidebar.less

This adds an import files button and staging area to the sidebar, and also includes a few other minor fixes.
Closes #540, #503, #532

Add staging area, import files button to sidebar + plus various fixes

---

README.md
app/background-process/dbs/archives.js
app/background-process/dbs/sitedata.js
app/background-process/networks/dat/library.js
app/background-process/ui/permissions.js
app/builtin-pages/views/library.js
app/package-lock.json
app/package.json
app/shell-window/pages.js
app/shell-window/ui/navbar.js
app/stylesheets/shell-window/toolbar-input-group.less
package-lock.json
package.json

Various fixes

---

app/background-process/protocols/dat.js
app/builtin-pages/com/files-list.js
app/builtin-pages/dat-sidebar.html
app/builtin-pages/views/library.js
app/builtin-pages/views/start.js
app/package-lock.json
app/package.json
app/shell-window/ui/sidebar.js
app/stylesheets/base/colors.less
app/stylesheets/builtin-pages/components/files-list.less
app/stylesheets/builtin-pages/library.less
app/stylesheets/components/buttons.less
app/stylesheets/components/messages.less

A running PR of usability improvements, while I do QA

Library usability tweaks

---

app/package-lock.json
package-lock.json
package.json
tasks/start-cli.js
tasks/start.js

Closes https://github.com/beakerbrowser/beaker/issues/581

Add the ability to npm link the binary

---

app/background-process/ui/modals.js
app/builtin-pages/views/select-archive-modal.js
app/stylesheets/base/colors.less
app/stylesheets/builtin-pages/select-archive-modal.less

Updates the UI of the modal to the `DatArchive.selectModal()` API
---
Previous version:

UI improvements to the Dat Archive Picker

---

app/background-process/browser.js
app/builtin-pages/views/dat-sidebar.js
app/lib/api-manifests/internal/browser.js
app/stylesheets/shell-window/toolbar-actions.less

Add Download .Zip to sidebar

---

app/background-process/protocols/dat.js

Closes https://github.com/beakerbrowser/beaker/issues/561
A site can now specify a path in `"fallback_page"` in their dat.json to set the 404 page. This is useful for nice 404 pages, and also for creating SPAs.

Add fallback_page behavior to dat hosting

---

app/builtin-pages/views/dat-sidebar.js
app/lib/web-apis/dat-archive.js
app/package-lock.json
app/package.json
app/shell-window/pages.js
app/shell-window/ui/navbar.js
app/shell-window/ui/sidebar.js
app/shell-window/ui/tabs.js
app/stylesheets/builtin-pages/dat-sidebar.less
app/stylesheets/shell-window/chrome-tabs.less
tests/lib/browser-driver.js

A collection of fixes and UI tweaks, mainly to do with the dat sidebar.

Bugfixes and tweaks

---

app/background-process/ui/context-menu.js
app/builtin-pages/views/dat-sidebar.js
app/lib/web-apis/dat-archive.js
app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/browser-menu.js
app/shell-window/ui/navbar/dat-sidebar.js
app/shell-window/ui/navbar/page-menu.js
app/shell-window/ui/navbar/site-info.js
app/shell-window/ui/sidebar.js
app/stylesheets/shell-window/toolbar-actions.less
app/stylesheets/shell-window/toolbar-dropdown.less
app/stylesheets/shell-window/toolbar-input-group.less

Adds a menu to the navbar of dat pages, to do common actions. This is to replace the dat sidebar with something a bit faster, more convenient, and less dauting

Dat page menu

---

app/stylesheets/shell-window/chrome-tabs.less

Hipper, fresher tabs

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
ISSUE_TEMPLATE
README.md
package.json

* Fixing up broken links in README.md and CONTRIBUTING.md
* Reinstate issue template
* Removing the optional opencollective postinstall step - just added a wall of text in the middle of npm install logs that few will see.

Fixing somethings broken by #621

---

app/background-process/ui/modals.js

https://github.com/beakerbrowser/beaker-error-constants/pull/1 has to land and be released before this can be merged.

Use ModalActiveError

---

app/background-process/debug-logger.js
app/background-process/protocols/beaker.js
app/background-process/ui/window-menu.js
app/lib/error-page.js

This should help us debug some of the networking issues in dat.

Add beaker://debug-log

---

app/background-process/protocols/dat.js

Updates the CSPs to allow connections to secure websockets.

Allow wss: connections from dat pages

---

app/shell-window/ui/tabs.js

Fixes an issue where favicons wouldn't be able to be updated dynamically via JavaScript.
Beaker kept checking for the first favicon instead of the last, this brings it inline with other browsers.

Dynamically Update Favicons

---

app/stylesheets/base/colors.less
app/stylesheets/shell-window/toolbar-actions.less
app/stylesheets/shell-window/toolbar-input-group.less

Decrease contrast of borders in the toolbar

---

app/background-process/ui/window-menu.js

Move beaker dev tools to avoid confusing users (close #647)

---

.travis.yml
app/package-lock.json
package-lock.json
tests/package-lock.json

Add .travis.yml to run tests on travis-ci.
Tests are failing on linux and sometimes some tests fail on mac too, but at least we can have a CI set up for the p2p browser :+1:

Run tests on travis-ci

---

README.md

I updated the readme to match to https://beakerbrowser.com/docs/install/#building-from-source
thanks!

Add Windows binary & Update build instructions

---

app/background-process/ui/context-menu.js

adding some familiar menu items:

Add back, forward and reload menuItems

---

README.md

Updated the license year

---

.travis.yml

dbus-x11 already installed on Travis

---

app/builtin-pages/com/onboarding-popup.js

adding the MF a

---

app/json-renderer.js
app/lib/fg/json.js
app/package.json
app/shell-window/pages.js
tasks/build/build.js

for issue: #961
Dependencies added: `json-formatter-js`
Possible Use Cases? : 
1. Beautifies the json
2. Helps developers understand json
3. ...addMore

Add JSON Rendering

---

app/shell-window/pages.js

Still todo: retain on back/forward

Restore the scroll position on page refresh

---

CONTRIBUTING.md

Since it was not clear to me initially how to debug the various parts of the application.

Add debug instructions to CONTRIBUTING.md

---

app/background-process/ui/context-menu.js
app/webview-preload.js

Implemented a Spellchecker for the Beaker Browser based on the electron3 branch.

Spellchecker

---

app/background-process/protocols/beaker.js
app/builtin-pages/com/add-watchlist-item-popup.js
app/builtin-pages/com/builtin-pages-nav.js
app/builtin-pages/views/library.js
app/builtin-pages/views/watchlist.js
app/builtin-pages/watchlist.html
app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/browser-menu.js
app/shell-window/ui/navbar/watchlist-notification.js
app/shell-window/ui/tabs.js
app/stylesheets/builtin-pages.less
app/stylesheets/builtin-pages/watchlist.less
app/stylesheets/shell-window.less
app/stylesheets/shell-window/browser-dropdown-menu.less
app/stylesheets/shell-window/watchlist-notification.less
tasks/build/build.js

Supercedes https://github.com/beakerbrowser/beaker/pull/1210
Still todo:

[WIP] Watchlist Feature and Built-in Page (PR 2)

---

app/builtin-pages/views/library-view.js

When in edit mode:
1. Use esc key `keyCode 27` to cancel editing of a file.
2. Use `CmdOrCtrl + S` shortcut to save editing of a file.

Updates to File Editor

---

app/shell-window/ui/navbar/browser-menu.js
app/stylesheets/shell-window/browser-dropdown-menu.less

Browser dropdown menu scrolls and resizes on height change.
https://i.gyazo.com/5421e70bdc0066db7890bd60d41535e9.mp4

Fix to #1229

---

tests/experimental-dat-peers-web-api-test.js

I'm including a test here for https://github.com/beakerbrowser/beaker-core/pull/18
I could not find any unit tests in the @beaker/core repo, so I assumed the integration tests here are sufficient. :)
I chose to create the `enableExperimentalDatPeersInDatJson` method from an existing test so that it won't depend on same test to run. Am definitely open to suggestions if this is not desirable.

test(datpeers): add ability to get own peer id

---

app/shell-menus/donate.js

Handle relative donation URLs in location bar

---

app/builtin-pages/views/library-view.js

Handle relative donation URLs in about page

---

app/bg/protocols/hyper.js

added workaround for electron/electron#24022 and electron/electron#24014

---

app/fg/shell-window/tabs.js

feature list
- drop url into tabs to open it.
- fix issue where opening too many tabs made you unable to click to close button
- added some space between the "create new tab icon" and "minimize icon" for the user to drag or double click
- double click the tabs shell will toggle between minimizing and maximizing

tabs changes

---

app/bg/ui/context-menu.js

resolves #1745 
Seems like most of the work was done and just commented out! Went ahead and added a "add to dictionary" button too.
Let me know if you have any feedback.

added 'add to dictionary' and top spellcheck options to context-menu
