app/background-process.js
app/background-process/api-manifests/browser.js
app/background-process/browser.js
app/background-process/open-url.js
app/background-process/ui/windows.js
app/builtin-pages/views/settings.js
app/shell-window.js
app/shell-window/ui.js
package.json

In order to make this work, `background-process` need to know when `shell-window` is ready, then send `file:new-tab` command to shell-window.
- add 'shell-window-ready' event to indicate shell-window is ready
- add app listener for `open-url` event.
- add `http` and `https` protocol to `package.json` so on OSX we can go `system perferences` -> `general` -> `default browser` and select beaker!
fix #77

add open-url support

---

app/shell-window/ui/navbar.js

A minor usability issue here. 
In Chrome, if we press ESC when editing navbar, the value of navbar will be reverted to the page's URL. In safari, we need to press ESC 2 times to achieve the same effect.
This PR will mimic the experience in Chrome, which take 1 ESC key press to revert the changes.
Feel free to close this PR if you don't like this behaviour.

revert any editing in navbar when ESC is pressed, not just remove focus.

---

app/package.json
app/webview-preload.js

This PR enables Fetch API, Service Workers, and CORS in sites served over dat://. Closes #95. Closes #90.
Makes some progress on https://github.com/beakerbrowser/beaker/issues/46. Still need a way to inject WebAPIs into ServiceWorkers.
There is an open issue, https://github.com/electron/electron/issues/7430. The electron API for enabling these features also enables the dat:// scheme to bypass CSP. Fairly certain we don't want that. Will open a tracking issue on this repo as well.

Update dat protocol policies to add support for Fetch API, ServiceWorkers, and CORS

---

app/shell-window/pages.js
app/shell-window/pages/live-reload.js
app/shell-window/ui.js
app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/drop-menu.js
app/shell-window/ui/tabs.js
app/stylesheets/shell-window/chrome-tabs.less
app/stylesheets/shell-window/toolbar-dropdown.less
app/stylesheets/shell-window/toolbar-input-group.less

[Demo video](https://www.youtube.com/watch?v=xcCNAAo8X8E)
This PR adds a toggleable Live Reloading mode to dat pages. Live reload watches the current page's dat for changes to the the file listing. Any time a file is changed in the dat, the page will refresh.
Note, it currently will reload after a change to *any page* in the dat. That's in case the change was made to, eg, a css file that's embedded in the page.

Add live reloading to dats

---

app/builtin-pages/views/archive.js
app/package.json

A dat site using DNS, such as `dat://hostless.website`, will now redirect to the archive key when viewing its files.

fix: dat archives using dns now correctly load in beaker:archive/

---

app/shell-window/pages.js

This should fix #68. @joehand and @xpollen8, if you experience double rendering after the next release (0.3.7) please re-open #68. I don't experience the bug, so I probably won't notice.

Inject a default background color, to avoid double-renders (close #68)

---

app/builtin-pages/views/archive.js
app/shell-window/pages.js
app/shell-window/ui/navbar.js
app/stylesheets/shell-window/toolbar-input-group.less
app/webview-preload.js
app/webview-preload/locationbar.js

This PR adds `window.locationbar.setSublocation({ title, value })` and `window.sublocation.clearSublociation()`. These APIs are only available to sites served over `beaker:` for now.
The API is used in the builtin archive view to cause the URL bar to look like this:
This solves a problem with URLs in the Archive Viewer. The viewer uses a URL scheme of `beaker:archive/{datKey}/{path...}`. We don't want users to share that URL - rather, we want them to share `dat://{datKey}/{path...}`.
This API solves that issue by showing the URL we intend to show. It, in a way, treats the Archive Viewer as a "browser within the browser." Thus, if the location is the archive viewer, then the sublocation is the the dat itself.
In the future, this might be generalized and made available for dat applications. …

Add sublocation API and use to improve archive view

---

app/shell-window/pages.js
package.json

This PR switches beaker to a custom build of Electron, which is located at https://github.com/beakerbrowser/electron
This incorporates a fix for #94 which will hopefully make its way into the main electron soon.

Custom Electron Build (which introduces fix for #94)

---

app/background-process/networks/dat/dat.js
app/background-process/networks/dat/web-api.js
app/builtin-pages/views/archive.js
app/lib/fg/import-web-apis.js
app/package.json

There were some cases where dats where not getting swarmed correctly. This PR fixes them, mainly by dropping out of the swarm and rejoining when the `upload` config toggles between true/false.

Fixes to dat swarming

---

app/background-process/ui/window-menu.js

All major browsers (Chrome/Safari/Firefox) use `cmd+{` and `cmd+}` as the hotkey to go to next/previous tab.
We should use the same hotkey for accessibility.

change tab traverse hotkey to be consistent with other major browsers

---

app/background-process/ui/windows.js

Following https://github.com/beakerbrowser/beaker/pull/187, this adds standard browser shortcuts `cmd+[` and `cmd+]` to navigate the history.

Add back/forward shortcuts on bracket keys

---

app/background-process/bkr.js
app/background-process/ui/windows.js

Closes https://github.com/beakerbrowser/beaker/issues/214
This is the server half of the update, which auto-opens the site created by `bkr dev`.

Add openUrl method to bkr server

---

app/background-process/api-manifests/external/dat.js
app/background-process/networks/dat/web-api.js
tests/dat-web-api-test.js

This PR adds the following new method aliases to the dat api:
- createSite: same as createArchive
- deleteSite: same as deleteArchive
- exists: wraps .stat to give true/false, instead of information. Since stat() throws if the target doesnt exist, this can be a convenient alternative
- listFiles: same as readDirectory

dat-web-api: add aliases createSite, deleteSite, exists, and listFiles

---

tests/package.json

Tests will fail if `bkr` 1.0 is installed before. `npm install` won't fix it. Requires manual upgrade.
```
1. bkr-test › bkr init
failed with "Command failed: /Users/poga/projects/beaker/tests/node_modules/bkr/build/bin/bkr init /var/folders/8m/93jxmmg550qcwp5ddm7zb7s00000gn/T/beaker-test-WsrZOC
Bkr version is 1 and minimum required is 1.1.0. Can you update bkr?
"
Bkr version is 1 and minimum required is 1.1.0. Can you update bkr?
ChildProcess.exithandler (child_process.js:211:12)
```
set the minimum required version should avoid further confusion.

Tests requires bkr v1.1.0, bump version

---

app/shell-window/ui/navbar.js

This PR makes the <kbd>CmdOrCtrl</kbd><kbd>l</kbd> shortcut select the contents of the address/location/nav/wonder/omni bar, even if it's already focused. This behavior is consistent with Chrome, Firefox, and Safari.
Please let me know if this should have a test somewhere!

select navbar content even when it's already focused

---

app/shell-window/ui/navbar.js
app/stylesheets/shell-window/toolbar-input-group.less

Closes https://github.com/beakerbrowser/beaker/issues/229
@zeke I decided to keep the shortened hash as-is, for now, so that it's very clear that a truncation is happening

Render hashes in the URL bar with pretty-hash, and gray the path

---

app/shell-window/swipe-handlers.js

As proposed in #254  add support for ctrl - mousewheel zoomIn/Out for ubuntu 16.10, should also work with windows. 
but .. need more info for mac.

proof of concept: add support for ctrl - mousewheel zoomIn/Out

---

app/background-process.js
app/background-process/networks/dat/dat.js
app/background-process/networks/dat/debugging.js
app/background-process/protocols/beaker.js
package.json

This PR:
- Enables read-verification during replication, solving a bug which would cause archives to fail to make progress in the network. (Big fix!)
- Improves logging (debugging)
- Adds the `beaker:internal-archives` site, so that you can quickly check the active archives and their various keys. (debugging)

Dat network bugfixing

---

app/background-process/networks/dat/dat.js
app/background-process/networks/dat/helpers.js

Do not auto-download the content of feeds.
This is part of a rather nuanced decision about how to use Dat.
Chiefly: unless the full history of the archive is retained via
external storage, you cannot prioritize the download of the full
content-feed.
Why? It's, in fact, somewhat obvious if you think about it: if
you aren't intent on storing the full history, and your external
storage doesn't properly give each historical version a unique
name, then you are going to end up writing new and old copies of
entries onto the same file as their pieces arrive.
So we must be much more specific about which blocks we request,
unless we intend to store the history, which we don't yet intend
to do.
The solution is simple enough: only download the files on-demand.
We'll add facilities for downloading …

Get your (dat) priorities straight

---

app/background-process/ui/window-menu.js

Add a Help menu for Windows and Unix like systems. 
I was searching quite hard to find the "About" Info. I didn't expect to find the stuff under "settings". ... but this may be a different issue / pr.
closes #256 if merged.

add Help menu for windows and linux like systems

---

app/shell-window/ui/tabs.js
app/stylesheets/shell-window/chrome-tabs.less

Previously we used CSS transform tricks, which had some really bad aliasing. This looks much better.

Update the shell-window tabs to use SVG edges.

---

app/shell-window/ui/navbar/site-info.js

Per @pmario's suggestion in #278, and per the decisions in #279, this PR updates the navbar UI as follows:
The "Learn more" link goes to https://github.com/beakerbrowser/beaker/wiki/Is-Dat-%22Secure-P2P%3F%22

Label dat as 'Secure P2P' in the navbar (close #279)

---

app/shell-window/pages.js

This focuses the webview after the dom-ready event fires, which fixes
a bug where inputs with the autofocus attribute would not focus unless
the webview was already focused.
Fixes #261

focus the webview after the dom-ready event

---

app/background-process/protocols/dat.js
app/webview-preload.js
tasks/build/build.js

Two speed improvements:
1. Use HTTP caching headers in the dat protocol
2. Avoid any runtime require() calls in the webview-preload by browserifying (big improvement), ~400-500ms.
There's still about 200ms getting lost somewhere, and I'm not sure where. Probably something about electron's webview behaviors. Removing the preload script doesn't get it all.

Improve dat load times

---

app/markdown-renderer.js
app/shell-window/pages.js
tasks/build/build.js

Watches for pages loaded that have type 'text/x-markdown' and injects a renderer.

Add builtin markdown rendering (on .md pages)

---

app/background-process/ui/windows.js
app/shell-window/swipe-handlers.js

This commit turns off swipe navigations when the user's cursor is
positioned over an element that has horizontal scrolling active.

Dont accidentally trigger navigations when horizontally scrolling.

---

app/lib/error-page.js
app/shell-window/pages.js

This changes the error page to handle:
* failed DNS resolution,
* failed TLS connection, and
* other errors with a general fallback page

Enhanced error page

---

app/builtin-pages/com/editor-header.js
app/builtin-pages/com/toast.js
app/builtin-pages/views/editor.js
app/stylesheets/builtin-pages/components/toast.less
app/stylesheets/builtin-pages/editor.less

This adds a reusable toast component that can be used on builtin pages. Toasts fade out and are removed from the DOM after just over a second.
```
toast.create('A toast message.')
```

Builtin toasts

---

app/shell-window/ui/navbar.js

I noticed that clicking on the number of peers on a `dat://` site currently opens `beaker://network`, which was recently renamed to `beaker://library`.
I changed the `onClickPeers` function to open `beaker://library` instead 🙂
I'm super excited for Beaker 0.7 😃 Cheers!

open beaker://library instead of beaker://network

---

app/background-process/networks/dat/library.js
app/background-process/web-apis/dat-archive.js
app/builtin-pages/com/library-files-list.js
app/builtin-pages/views/library.js
app/package.json
app/stylesheets/builtin-pages/library.less

- Fix performance in the file-activity watching algorithm (https://github.com/beakerbrowser/pauls-dat-api/commit/56ad3cecc717b09ba4392664fed8d5c392272f5d). This speeds up both the library view and archive loading perf in general.
- Improve Library-view performance by loading the file-tree on-demand, instead of everything at once
- Improve Library-view performance by paginating history

V0.7 performance improvements for dat

---

app/background-process/web-apis/dat-archive.js
tests/dat-archive-web-api-test.js

This was a security vulnerability that needed to be closed.
As convenient (and fun) as self-modifying sites are, they dont put a proper perimeter around the application code. Without this policy, it would be possible for an included library to overwrite app code. That would be a Bad Thing.

Disallow self-modifying dats

---

app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/site-info.js
app/stylesheets/shell-window/toolbar-input-group.less

This fixes the security UI on error pages and adds a "Not secure" label on pages with HTTPS errors

Update security UI on error pages

---

app/background-process/networks/dat/library.js
app/background-process/ui/modals.js
app/background-process/web-apis/archives.js
app/builtin-pages/views/create-archive-modal.js
app/builtin-pages/views/library.js

When you click "Edit site info" in the library for readonly archives, you now get this modal:

V0.7 handle readonly siteinfo

---

app/builtin-pages/com/downloads-list.js
app/builtin-pages/com/toggleable.js

This makes it possible to close a toggleable element with ESC and clicking anywhere on the page.
@pfrazee, do we also need to remove the `keyup` event listeners like I do for the `document`'s `click` event?

Update how toggleables can be closed

---

README.md
app/background-process/browser.js
app/background-process/dbs/archives.js
app/background-process/networks/dat/library.js
app/background-process/protocols/dat.js
app/background-process/ui/modals.js
app/background-process/web-apis/archives.js
app/background-process/web-apis/dat-archive.js
app/builtin-pages/com/archive-changes.js
app/builtin-pages/com/files-list.js
app/builtin-pages/views/create-archive-modal.js
app/builtin-pages/views/fork-archive-modal.js
app/builtin-pages/views/library.js
app/lib/api-manifests/internal/browser.js
app/lib/const.js
app/package.json
app/stylesheets/builtin-pages/fork-archive-modal.less
app/stylesheets/builtin-pages/library.less
tests/archives-web-api-test.js
tests/dat-archive-web-api-test.js

After some QA, we've hit on some improvements that this PR should make:

Changes to sites folders and dat.json handling

---

app/background-process/protocols/beaker.js
app/background-process/ui/modals.js
app/background-process/web-apis/archives.js
app/background-process/web-apis/dat-archive.js
app/builtin-pages/select-archive-modal.html
app/builtin-pages/views/basic-auth-modal.js
app/builtin-pages/views/create-archive-modal.js
app/builtin-pages/views/fork-archive-modal.js
app/builtin-pages/views/select-archive-modal.js
app/lib/api-manifests/external/dat-archive.js
app/lib/web-apis/dat-archive.js
app/stylesheets/builtin-pages/create-archive-modal.less
app/stylesheets/builtin-pages/select-archive-modal.less
app/stylesheets/components/modal.less
tasks/build/build.js
tests/dat-archive-web-api-test.js

This adds:
- A new `DatArchive` method, `selectArchive()`, which prompts the user to select or create an archive and returns the URL of the selected archive
- A new modal for selecting an archive

DatArchive.selectArchive

---

app/background-process/web-apis/dat-archive.js
app/lib/web-apis/dat-archive.js
app/package.json
tests/dat-archive-web-api-test.js

Adds an option to `DatArchive` API's `readdir()`
```js
await archive.readdir('/', {stat: true})
/* => [
{name: 'foo', stat: {...}},
...
]*/

Add {stat:} opt to DatArchive.readdir()

---

app/shell-window/pages.js
app/webview-preload.js
app/webview-preload/redirect-hackfix.js

Electron has an ongoing problem with redirects. See https://github.com/electron/electron/issues/3471. This updates our hackfix.
This was only tested with simple auth, not 2FA.

Fix: Can now log in to Twitter (close #453)

---

app/background-process/web-apis/dat-archive.js
app/lib/web-apis/dat-archive.js
app/package-lock.json
app/package.json
tests/dat-archive-web-api-test.js

This makes it possible to do the following things:
```js
await DatArchive.resolveName('dat://foo.com/bar')
await DatArchive.resolveName(window.location)
new DatArchive('dat://foo.com/bar')
new DatArchive(window.location)
```

Add support for DNS shortnames in the DatArchive API

---

app/shell-window/pages.js

(^ Previously it would have just shown the URL in the tab title)

Fallback the page title to the site title if none is given (close #507)

---

app/background-process/networks/dat/debugging.js
app/background-process/networks/dat/dns.js
app/background-process/protocols/beaker.js
app/background-process/protocols/dat.js
app/background-process/ui/window-menu.js
app/background-process/web-apis/archives.js
app/background-process/web-apis/dat-archive.js
app/lib/api-manifests/internal/archives.js
app/lib/web-apis/beaker.js
app/package-lock.json
app/package.json

Closes https://github.com/beakerbrowser/beaker/issues/502
Adds `beaker://dat-dns-cache` and makes hard-reload clear the current dat-dns cache

Dat-DNS cache controls

---

app/background-process/networks/dat/library.js
app/background-process/web-apis/archives.js
app/builtin-pages/views/library.js

Previously, saved read-only dats were synced to a local staging path. This had two problems:
1. Poor performance (https://github.com/beakerbrowser/beaker/issues/541)
2. The folder placed on disk was confusing to users, who thought they'd be able to edit the files. In fact, they could, but when the source Archive did an update, their changes were overwritten.
This PR accompanies some already-made UI changes, which gets rid of the local staging path for readonly dats, and instead just syncs to internal storage. The final step will be to add a "Download as Zip" control, which lets the user get snapshots of the archive. That will be a future PR.

Simplified saved readonly Dat archives

---

app/background-process/networks/dat/library.js

This solves an issue with bloated peer counts

Fix: properly remove replication-streams in error events 

---

app/shell-window/ui/navbar.js
app/shell-window/ui/navbar/dat-sidebar.js
app/shell-window/ui/sidebar.js
app/stylesheets/shell-window/toolbar-actions.less
app/stylesheets/shell-window/toolbar-input-group.less

Can now click the peer count, and easily tell if the panel is open

Improve sidebar controls in the navbar

---

app/background-process/web-apis.js
app/lib/bg/rpc.js
app/webview-preload.js

Closes https://github.com/beakerbrowser/beaker/issues/553
Exposing the DatArchive to HTTPS makes it possible for traditional service-based applications to publish and consume using Dat. This has benefits to everybody involved. For the standard end-user, you get more control over their data, and less lockin. For the service developer, you get a cost-saving technology, and the capabilities of the service itself.
As of this PR, a page served over HTTPS can access [`DatArchive`](https://beakerbrowser.com/docs/apis/dat.html).

Add DatArchive API to HTTPS sites

---

app/lib/bg/rpc.js
app/webview-preload.js

This is a follow up to https://github.com/beakerbrowser/beaker/pull/586
Makes it possible to access DatArchive APIs from `http://localhost`, which is important for testing

Allow http://localhost to access DatArchive apis

---

app/shell-window/ui/prompts/permission.js
app/stylesheets/shell-window.less
app/stylesheets/shell-window/promptbar.less

Before:
After:
The link was always there ("My Web site" should be blue in the "before" pic) so that's what I set out to fix. Then I figured I'd touch up the button styles while I was at it.

Fix up styles on the write permissions prompt

---

app/background-process/dbs/archives.js
app/background-process/dbs/profile-data-db.js
app/background-process/dbs/schemas/profile-data.v4.sql
app/background-process/networks/dat/library.js
app/background-process/web-apis/archives.js
app/builtin-pages/views/dat-sidebar.js
app/builtin-pages/views/library.js
app/lib/api-manifests/internal/archives.js
app/lib/web-apis/beaker.js
app/stylesheets/builtin-pages/dat-sidebar.less
app/stylesheets/builtin-pages/library.less
tests/archives-web-api-test.js
tests/dat-archive-web-api-test.js

We felt we could make the process of saving sites more clear. Instead of "Sync for offline," we now have a button to "Add to library," and then additional settings for configuring the auto-downloader.
We also have a UI planned for configuring auto-uploading, but this is blocked until support for no-upload is added to hypercore's replicate() method:

Improvements to dat configuration

---

app/background-process/dbs/archives.js
app/background-process/networks/dat/library.js
app/background-process/web-apis/archives.js
app/background-process/web-apis/dat-archive.js
app/builtin-pages/views/create-archive-modal.js
app/builtin-pages/views/fork-archive-modal.js
app/builtin-pages/views/select-archive-modal.js
tests/dat-archive-web-api-test.js

Closes https://github.com/beakerbrowser/beaker/issues/591 and https://github.com/beakerbrowser/beaker/issues/544
We decided this metadata offers pretty little value, but it does create the potential for accidentally leaking private information.

Deprecation: Remove createdBy and forkOf from dat.json manifests

---

app/background-process/networks/dat/library.js
app/background-process/protocols/dat.js
app/background-process/web-apis/dat-archive.js
app/builtin-pages/com/files-list.js

This PR makes it so that a dat.json manifest is written to the staging area, and put into the user's attention & control.
@millette this is a change you've been asking for.

Expose dat.json to the staging area

---

app/background-process/networks/dat/directory-listing-page.js
app/background-process/protocols/dat.js

Closes https://github.com/beakerbrowser/beaker/issues/535
You can now specify a `"web_root"` in your dat.json to control which folder beaker serves out of

Add web_root behavior to dat hosting

---

app/background-process/ui/context-menu.js
app/shell-window/command-handlers.js
app/shell-window/ui/navbar/dat-sidebar.js
app/shell-window/ui/sidebar.js

After using the dat sidebar for a while, we decided it's handy, but really only for cases where you're doing work on a site (or inspecting the site). So we decided to model it after devtools.
Now, instead of there being a persistent navbar button, you open it with this:
It also now isolates its "open" state to individual tabs, like the devtools.

Make the sidebar a less front-and-center tool

---

app/background-process/protocols/dat.js

See the discussion in https://github.com/beakerbrowser/beaker/issues/552
This PR relaxes the CSP so that dat:// sites can access http/s origins. In a future PR, we will add an opt-in setting which defaults to the previous restrictive CSP, and then prompts the user to relax the CSP for a site that needs it.

Relax the CSP for dat:// sites

---

app/lib/web-apis/dat-archive.js
tests/dat-archive-web-api-test.js

The `DatArchive.selectArchive()` method is supposed to return a new DatArchive. Somehow I misimplemented it before, and returned just a `url`.
Fixing this now. Some people's apps may break (sorry!).

Fix: Correctly return a DatArchive from selectArchive

---

README.md

I was wondering about the default values for storing data and such and couldn't find it in the readme so I thought I'd update it with the information I gathered.
Cheers

Document default values for env vars

---

app/background-process/web-apis/dat-archive.js
app/package-lock.json
app/package.json

Currently, an archive `diff()` call will incorrectly mark some files as "changed." This occurs because the diffing algorithm only checks the 'modified time' of files to decide whether they have been changed. The modified time is updated too frequently. It is updated any time the file's content is written, which means that file-writes which do not change the actual content are still registered as "changes."
See https://twitter.com/conoro/status/890274540617641984 for the negative effects of this.
With this PR, we update the diffing algorithm to compare the full content of a file, which will remove all false-positives.
**Note**. This was tried before and it was too slow. Since then, I added the {shallow:} opt to the diffing algorithm, and I'm hopeful that will keep this algorithm …

Reduce false positives in diff() calls - DatArchive Staging Area

---

app/background-process/web-apis/dat-archive.js
app/shell-window/pages.js

This PR updates the "dat not found" behavior. When you get the "Timed out while searching" page, if Beaker finds the dat after displaying that page, it will now automatically reload the page and show the content.

Automatically reload the page if a timedout dat is found

---

app/background-process.js
app/background-process/browser.js
app/background-process/ui/windows.js
app/stylesheets/shell-window/toolbar-actions.less
tests/archives-web-api-test.js
tests/browser-test.js
tests/dat-archive-web-api-test.js

This PR updates Beaker so that it minimizes to the tray by default, rather than quitting. This keeps people's files online more reliably.
Closes #650

Add 'quit to tray' for persistent execution

---

app/shell-window/ui/navbar/bookmark-menu.js

I'm wondering if this could be a good change. Other browsers such as Chrome and Firefox seem to have this behavior (when you click to edit a bookmark, the title is automatically selected). It's a very minor change, but I've been thinking about it every time I open the bookmark menu dropdown, so I figured it might be a good idea to do a pull request 😛

select the title input when opening the bookmark menu dropdown

---

app/background-process/ui/windows.js
app/shell-window/command-handlers.js
app/shell-window/pages.js

this adds two shortcuts I have muscle memory around from other browser : 
- `ctrl` + `PageDown` to go to the next tab  ( `PageUp` is prev tab)
- `ctrl` + `9` to go to the last tab

(Beaker 0.8) tab shortcuts

---

app/background-process/ui/window-menu.js

I didn't know you could reload the shell-window without rebuilding :japanese_goblin: :sweat_drops: 
I guess I should have looked for or asked for advice on dev flow in this app.
Anyway, this adds shortcuts for accessing what I need to access right now.

add keyboard shortcust for shell window dev

---

app/shell-window/ui/navbar.js

@pfrazee going after some low handing fruit...
Added a right click context so you can `cut`, `copy`, `paste` in `locationInput`:

Add onContextMenu to locationInput

---

app/background-process/ui/windows.js

For a while, I've noticed that Beaker doesn't remember the window state when I resize the browser window to take the full width of my screen (in other words, when I maximize it). I have a large display with a resolution of 2048 by 1152, and by default, Beaker sets the width of the browser window to 1800 pixels (because of [this line](https://github.com/beakerbrowser/beaker/blob/7ee2e867f0dfc30a4e1c7ba81886fd7f88641e00/app/background-process/ui/windows.js#L211)).
After digging in the source code a bit, I noticed that Beaker doesn't save the window state if the browser window is maximized (see [this line](https://github.com/beakerbrowser/beaker/blob/7ee2e867f0dfc30a4e1c7ba81886fd7f88641e00/app/background-process/ui/windows.js#L247)). So this explains the issue I am having.
Instead of not …

Save window state if the window is maximized, but not if it's in fullscreen mode

---

app/shell-window/pages.js

Fix issue reported by @taravancil (https://github.com/beakerbrowser/beaker/issues/671) that prevented URL from keeping active when other pages finished loading.

Fix URL typing interruption

---

app/background-process/ui/permissions.js
app/package.json

I wanted an adblocker for sites and for youtube.
This seems to work, but the code is sitting in the wrong place :man_shrugging: (TODO)
| Before | After | 
|:---:|:---:|
| ![selection_423](https://user-images.githubusercontent.com/2665886/32401442-77aab4e2-c173-11e7-9bda-b32c0145ae2b.png) | ![selection_424](https://user-images.githubusercontent.com/2665886/32401444-7eed5746-c173-11e7-98bb-a518d93262ad.png) | 
I think this also blocks **youtube ads** phew
I cast around for simple setups, here's a reference of what I found for posterity: 
- https://electron.atom.io/docs/api/web-request/ - how to intercede
- https://www.npmjs.com/package/is-ad (<< using this)
- brave's setup : 
- https://github.com/brave/ad-block bad documention
- browser adblock initialisation : …

add minimal ad-blocker

---

app/shell-window/ui/navbar.js

Written to solve #679. To reproduce:
1. Start typing a URL of a previously visited page.
1. Beaker will find the most-visited page starting with the value you entered, autocomplete the URL, and select the relevant result in the autocomplete dropdown.
1. Hit "Backspace" to delete the autocomplete and return to the top dropdown result.

URL bar autocomplete

---

app/background-process/open-url.js
app/background-process/ui/windows.js
app/shell-window.js
app/shell-window/command-handlers.js
app/shell-window/pages.js
app/shell-window/ui.js

**Do Not Merge** This is a work-in-progress pull request to fix #737. Right now this branch just always restores the previous window state. I still need to make sure that this only happens on crash. Would also probably want to bring up a prompt to ask if they want to restore state. I know some browsers also have a "Restore tabs from last time" setting to have this always trigger, so I'm not sure if I should try to sneak that into this pull request as well. Mainly I want to get the code in front of y'all to see if you have any feedback on the approach. Just want to see if I'm on the right track here. Please feel free to ignore any `console.log` statements I'll try to remove those before all's said and done.

[WIP] Restore Window State on Crash

---

app/background-process/ui/windows.js

This PR adds and registers a new event handler function for handling App Commands emitted by a Windows OS. Only the 'browser-backward' and 'browser-forward' commands are being handled by this code. When either are handled, the appropriate calls are made to navigate forward or backward in browsing history.

Implemented mouse browser back/forward navigation (Windows only :c)

---

app/background-process/ui/window-menu.js

Open preferences with <kbd>Cmd</kbd><kbd>,</kbd> on macOS

add a keyboard shortcut to preferences on mac

---

app/background-process/dbs/settings.js
app/background-process/ui/windows.js
app/builtin-pages/views/settings.js
app/stylesheets/builtin-pages/settings.less

This pull request adds the **"General"** settings page that includes an **"On Startup"** option that lets users choose what pages to display on startup. You can either choose to open up a blank page (the default) or you can open up your previously opened tabs and windows. This is an extension of the work done in #840. This should resolve issue #737. This PR adds a new `custom_start_page` setting to make it work.
@taravancil I'm guessing you might have an opinion on the page name and placement of this setting. I just went with a "General" page because that's where I saw this setting located in other browsers, but if you want it moved let me know.
(p.s. It seems the Settings page navigation is hidden at the moment on the 0.8 branch. Something to do with the absolute positioning?)

Add setting to always restore previouslly opened tabs.

---

tasks/start-cli.js

After this fix you can run `beakerbrowser` anywhere on your machine to launch it after npm linking

Fix running beakerbrowser outside the repo

---

app/shell-window/ui/navbar/browser-menu.js

This fixes a small UI bug where keyboard shortcut lto open browsing History in dropdown menu was incorrect for Linux.
Closes #904
As always, thanks for making Beaker -- 0.8 is  looking awesome!

Show browser history shortcut in dropdown menu by platform:

---

app/background-process/ui/context-menu.js

In Chrome and Firefox you can highlight some text in a webpage, right-click it, and search Google for that text. I missed that feature so I implemented it for searching DuckDuckGo. 
It works for non-editable text...
and editable text
and doesn't appear if you haven't selected and right-clicked some text.

Added DuckDuckGo search to context menu

---

README.md

Looks like the license was un-modified in https://github.com/beakerbrowser/beaker/commit/6c9304d0bfab15e77c6801ed21bd7a927e065bbf.

MIT License isn't modified

---

app/background-process/ui/windows.js

When using beaker browser, I find myself missing the alt + d shortcut to focus the address bar (which is available in firefox and chrome.)
While investigating what the situation is on Mac, I noticed there's an alternative 'ctrl + l' and that beaker implements that here: https://github.com/beakerbrowser/beaker/blob/bbed013686ddf0f8d78c9afbc8e4dbc3da3780d9/app/background-process/ui/window-menu.js#L108
(Oh, if I hold 'alt' I can see it labelled within the file menu.)
If you are interested in having the 'alt + d' shortcut as well, would you prefer that I instead either:
* Make it possible to define an accelerator of the form 'CmdOrCtrl+LOrAlt+d'
* Make it possible to define an array of accelerators in the menus ?
Or is this pull request fine as is?

Add a shortcut for focusing the address bar (alt + d).

---

app/background-process/ui/window-menu.js
app/shell-window/command-handlers.js
app/shell-window/ui/navbar.js

menu and keyboard shortcuts for find next (cmd+G) / previous (Shift+cmd+G). Remove the dependency on the click event, i assume there will only ever be one Find window in the ui so we can look it up directly.

Implement find-next and find-previous shortcuts

---

app/background-process/ui/permissions.js
app/background-process/web-apis.js
app/background-process/web-apis/experimental/global-fetch.js
app/background-process/web-apis/experimental/library.js
app/lib/api-manifests/external/experimental/global-fetch.js
app/lib/perms.js
app/lib/web-apis/experimental.js
tests/experimental-global-fetch-web-api-test.js

Traditional web applications are able to make cross-origin requests by proxying through their own servers. That's not a possibility for Dat's serverless apps, which is a problem for a lot of apps. For instance, what if you wanted to fetch "open graph" metadata for a site before posting it on a social profile app (ie fritter).
This PR solves this issue with a new Labs API called `experimental.globalFetch`. It is functionally similar to `fetch()` except for a few key differences:
- Currently only `HEAD` and `GET` are supported.
- A permission prompt is raised for each request to a new origin.
- CORS policies are not applied, and so the site can send a request to any possible service.
- Cookies/credentials are never sent.
For each new origin contacted, a new permission prompt will be …

Add experimental.globalFetch() Labs API

---

app/builtin-pages/com/archive-history.js
app/lib/web-apis/dat-archive.js
tests/dat-archive-web-api-test.js

Currently, if you want to access a specific revision of an archive, you have to manipulate the URL. This snippet is an example of what this is like:
```js
// read from latest
let vi = archive.url.indexOf('+')
if (vi !== -1) {
archive = new DatArchive(archive.url.slice(0, vi))
}
```
This PR adds a `checkout()` method to the `DatArchive` which makes it easy to do this. If no number is passed in, you will get latest. Examples:
```js
var v5 = archive.checkout(5) // get revision 5
var latest = archive.checkout() // get latest
await archive.checkout(5).readdir('/') // read the files listing at root of revision 5
```

Add DatArchive#checkout() method

---

app/stylesheets/shell-window/donate-menu-dropdown.less

This isn't really a complete fix, it'll still look a bit wild on screen but it should keep the URL from escaping the dropdown for the Donate button (I tested the feature with a dat:// URL to come across this bug).
Could've used "word-break: break-word" or "overflow: hidden" instead but that's a design thing and I'm not sure I've good input to share there.

Donate dropdown overflows with long URLs

---

app/background-process/ui/windows.js

"Restore session" vs "Cancel" is confusing if you are not familiar with the software - it felt like it was going to cancel loading the app.  This makes it clearer what the choices are I think.

Make restore session dialog more understandable

---

app/shell-window/pages.js

Closes #704
This PR adds support for rubber band scrolling (#704). 
According to a `TODO` comment in the source code, this was meant to be fixed when issue https://github.com/electron/electron/issues/9233 was resolved. Although the issue has not been marked as `closed` there are comments that say that the issue is no longer a problem in Electron `2.0.0`
https://github.com/beakerbrowser/beaker/blob/73461db7cf790518f9b3e52b015f772164a19f68/app/shell-window/pages.js#L1082
> Rubber band scrolling is working as expected now.
Added `scrollBounce` to `<webview>` `webpreferences` attribute in `createWebviewEl`

Enable rubber band scrolling on <webview> elements

---

README.md

I was installing Beaker Browser in a clean install of Fedora and ran into an error that took me a bit to locate. I didn't realize I already had this dependency in my previous install, so this PR is to help new users on Fedora :smile_cat: 
Note: I ran `npm burnthemall`, `npm install` and `npm run rebuild` before I found this missing dependency. Installing this dependency helped resolve the issue in the screenshot below

Add libXScrnSaver dependency

---

app/background-process/browser.js
app/builtin-pages/com/settings/favicon-picker.js
app/package.json
app/stylesheets/builtin-pages/components/favicon-picker.less

Had to add a new package `'to-ico'` in order to convert `.png` files to `.ico` format
Added button inside of favion picker to upload favicon. This opens a dialog to choose the favicon file. Limited to `.jpg`, `.png`, and `.ico`.

Added in feature to upload a favicon

---

app/builtin-pages/views/library-view.js
app/package.json

Renders a preview max `1e5` (100,000 bytes) in size. When you click the pencil and enter edit mode, the full file will be shown in the editor. Not showing on initial viewing to prevent rendering a large file.

Fix to #1214

---

app/builtin-pages/views/library.js

Allow dat:// to be apart of the dat key search.
Now works with just keys or dat://key

Quick fix to library search

---

app/background-process/ui/window-menu.js

closes #1287 
This PR disables a bunch of menu items that don't apply when no windows are opened, and launches a new window for actions that would otherwise open a tab, such as showing Preferences.

Set application menus when there are no open windows

---

app/stylesheets/shell-window/toolbar-input-group.less

Ref #1289 
This is just a one-liner to use tabular (fixed width) numbers for the peer counter. It was buggin' me too!
Now the counter will only change width when the number of digits changes. Happy holidays!

Use tabular numbers for address bar peer counter

---

app/shell-window/pages.js

On Beaker 0.8.2 I've noticed the builtin pages intermittently lose focus when navigating between them. Focusing another UI element in Beaker, and then clicking back in restores the focus. 
Here's a gif to illustrate what I mean:
I think this is a case of https://github.com/electron/electron/issues/14474
In this PR I'm following the workaround discussed in the electron issue, calling the webview's blur/focus methods on domready. This fixes the problem for me, autofocus works properly and I can navigate around the forms as expected.

Builtin pages lose focus after navigation

---

README.md
app/background-process/browser.js
app/background-process/hidden-windows.js
app/background-process/ui/windows.js
app/package.json
app/shell-window/pages.js
app/shell-window/ui/tabs.js
app/shell-window/webview-async.js
app/stylesheets/shell-window/chrome-tabs.less
package.json
tasks/rebuild.js
tasks/util-run.js
tests/experimental-dat-peers-web-api-test.js

Update to Electron 4

---

app/background-process.js
app/background-process/nat-port-forwarder.js
package.json

This is a partial fix for #1246. This will only work for one  device behind the same NAT as all clients wants to  control the same port rather than using normal random port assignment. This would have to retry and negotiate with the router in addition to tracking which port that should be announced to the tracker.
I implemented this in Beaker rather than Dat as this required the least amount of change and will work as a temporary solution while we wait for Hyperswarm. This commit should be reverted when Hyperswarm is done.
I’ve evaluated all the UPnP NPM modules I could find and none of them are all that great. They silently don’t handle errors and don’t negotiate IGDv1/v2 properly. There are two common ways for port forwarding (permanent and ttl-leased) usually depending on the available …

UPnP support

---

app/builtin-pages/views/library-view.js
app/new-shell-window/navbar/location.js
app/shell-menus/browser.js
app/shell-menus/donate.js
app/shell-window/ui/navbar/browser-menu.js
app/shell-window/ui/navbar/donate-menu.js

Browsers have used hearts and stars to mean bookmarks interchangeably over the years; and still do to this day. Change the icon to avoid confusion with the bookmarking functionality and make it clearer what the button does.
dat://e71784fbaaac13e7a1b20ba39d8149b2ba893171204672575eab8b4fd0758ec3/1387/image.png
Icon changes (all were [fa-hearts](https://fontawesome.com/icons/heart?style=solid) previously):
* [fa-donate](https://fontawesome.com/icons/donate?style=solid) in location bar
* [fa-donate](https://fontawesome.com/icons/donate?style=solid) in Library: Archive: Settings
* [fa-donate](https://fontawesome.com/icons/donate?style=solid) in hamburger menu (donate to Beaker)
* [fa-hand-holding-usd](https://fontawesome.com/icons/hand-holding-usd?style=solid) in donation pop-out window
* …

Replace ambiguous heart donation icons

---

.github/ISSUE_TEMPLATE.md

The [Dat forum](https://dat.discourse.group/) is open for registration and can help keep support requests and discussions out of the bug tracker. It also provides better search and forum tools.

Nudge people towards the forum when filing bugs

---

app/assets/templates/website/styles.css

Just fixing a tiny typo in the `styles.css` template. 🙂

Fix typo in styles.css

---

app/userland/webterm/js/main.js

This patch changes the history/input handling code of the
webterminal to use keycodes instead of the name of keys.
Using direct keycodes means that different keyboard layouts or
custom input methods will work properly.
The code of the key-mapping object is taken from the `mousetrap`
library which is licensed under the Apache-2.0 license.

made webterm use keycodes to detect special/control keys

---

app/bg/hyper/daemon.js

Right now `setup` will attempt to start a daemon regardless of if a daemon is currently running on the system. 
This change first checks if there's an external daemon running before following through with the rest of the daemon setup. If the first client can't connect, the previous `setup` approach will proceed.

Attempt to connect to external daemon earlier

---

app/bg/ui/window-menu.js

I've had this PR in mind for a while and finally decided to go ahead and implement it!
On [Chrome](https://support.google.com/chrome/answer/157179?hl=en), [Firefox](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs) and [Brave](https://support.brave.com/hc/en-us/articles/360032272171-What-keyboard-shortcuts-can-I-use-in-Brave-) on macOS, one of the keyboard shortcuts I use the most is ⌘ + Option + Right arrow (jump to the next open tab) and ⌘ + Option + Left arrow (jump to the previous open tab).
On Windows and Linux, the equivalent shortcut is Ctrl + PgDn or Ctrl + PgUp. This is also the shortcut currently used in Beaker on Windows and Linux. But on macOS, it's currently ⌘ + PgDn and ⌘ + PgUp. I'm not aware of any browsers on macOS that …

change previous/next tab keyboard shortcut on macOS

---

app/bg/hyper/capabilities.js
app/bg/hyper/dns.js
app/bg/protocols/hyper.js
app/bg/web-apis/bg.js
app/bg/web-apis/bg/capabilities.js
app/bg/web-apis/bg/hyperdrive.js
app/bg/web-apis/fg/external.js
app/bg/web-apis/manifests/external/capabilities.js
app/package.json

Doing this one as a PR for documentation. (Sorry for the malformed initial PR; I fat-fingered it.)
This PR adds a "capability URL" and Web API. These are capabilities in the [capabilities security model](https://en.wikipedia.org/wiki/Capability-based_security) sense. They are opaque URLs which map to hyperdrives while hiding the URL.
The hyperdrive capability URL uses a special `.cap` pseudo-TLD. They are formed as `hyper://{random-base32-id}.cap/`. I decided to use a pseudo-TLD instead of a new URL scheme so that the URL scheme does not change from other hyperdrives.
The purpose of capability URLs is to provide security primitives for constrained access to a hyperdrive. The default security model of a hyperdrive is that the pubkey provides read access locally and over the network. …

Add hyperdrive "capability" URLs

---

app/userland/editor/js/main.js

Considering that this context menu also shows up when you right-click on a folder, I think it could make sense to rename it to Export. This is also how it's called in the Files Explorer. I also renamed it to Export for the actions menu just to be consistent but could also make sense to leave it like that.

Minor change

---

CONTRIBUTING.md

This updates `CONTRIBUTING.md` to point to `scripts/package.json` since there is no `package.json` in the project root folder.
* Run through instructions provided in `CONTRIBUTING.md` underneath `To build:`.

Update CONTRIBUTING with correct path and node version

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

- Adjust field titles.
- Remove unneeded "Browser" field under "Desktop".
- Convert field descriptions to comments to ensure that users don't submit them when skipping a section.

Clean up issue templates

---

app/lib/urls.js

fixes issue #1669. Another massive pull request! `about:blank` redirects correctly, but all other required `about:` uri's redirect to `about:blank#blocked`. I am not sure if that is chromium issue or how important it is, however, this is a step in the right direction.

about URI's accepted as valid as opposed to triggering search

---

app/bg/ui/context-menu.js

Super tiny typo in context-menu that throws error when no default search engine is selected. Is just a fallback and will probably never run, but you never know.

added missing s to searchEngine

---

app/bg/protocols/hyper.js

fixes an edge case where if the stream emits readable before electron gets a chance to attach the listener, it deadlocks

fix onreadable edgecase

---

app/bg/web-apis/bg/hyperdrive.js

resolves #1642 
Seems to work, and still checks to see if the drive contains a `.cap` filetype

allows mounting file with specified version

---

app/userland/history/css/main.css.js

I noticed that the browsing history tab had overlapping elements when opening DevTools or using split windows on my 1366x768 monitor. 
**Before:**
I fixed it by adding a media query which sets a left margin when reaching the breakpoint. I then adjusted the width of the navbar slightly to remove the remaining overlap.
**After:**

Fixed overlapping UI in the history tab

---

app/bg/protocols/hyper.js

Currently the mime type is purely detected based on file name. This is a challenge if the file name does not include the actual file type.
Speaking with @mafintosh and @digli me together with @digli concluded that we could do two things:
1. Actually read a chunk and use that to detect mime type
2. Save the mime type to the metadata and use that explicit mime type rather than implicitly derive it from the file
This PR contains both approaches – one commit for each.

Improve mime type detection for hyper://
